### ISSUE TITLE
Unable to import statements which contain tag: #db/fn

### ISSUE THREAD

**Issue by nikolayandr** [scalamolecule/datomic-client-api-java-scala#2]
Hi, the next statement cant be transacted:

```
[{:db/id    #db/id [:db.part/user]
  :db/ident :my.fn/incrementCounter
  :db/doc   "Function that increments value of passed <code>KeyGenerationCounter</code>"
  :db/fn    #db/fn {:lang   "clojure"
                    :params [db e]
                    :code   [[:db/add e
                              :KeyGenerationCounter/value
                                      (-> (d/entity db e) :KeyGenerationCounter/value (+ 1))]]}}]
```

The next error happens:

```
Caused by: us.bpsm.edn.EdnException: Unable to compute a consistent method resolution order for datomic.function.Function.
	at us.bpsm.edn.protocols.C3.methodResolutionOrder(C3.java:48)
	at us.bpsm.edn.protocols.Protocols$ProtocolImpl.lookup(Protocols.java:106)
	at us.bpsm.edn.printer.Printers$1.printValue(Printers.java:136)
	at us.bpsm.edn.printer.Printers$5.eval(Printers.java:274)
	at us.bpsm.edn.printer.Printers$5.eval(Printers.java:268)
	at us.bpsm.edn.printer.Printers$1.printValue(Printers.java:142)
	at datomicClient.ClojureBridge$$anon$1.$anonfun$eval$1(ClojureBridge.scala:43)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at datomicClient.ClojureBridge$$anon$1.eval(ClojureBridge.scala:43)
	at datomicClient.ClojureBridge$$anon$1.eval(ClojureBridge.scala:40)
	at us.bpsm.edn.printer.Printers$1.printValue(Printers.java:142)
	at us.bpsm.edn.printer.Printers.printString(Printers.java:74)
	at datomicClient.ClojureBridge.edn(ClojureBridge.scala:94)
	at datomicClient.ClojureBridge.edn$(ClojureBridge.scala:93)
	at datomicClient.Invoke$.edn(Invoke.scala:13)
	at datomicClient.Invoke.$anonfun$transact$1(Invoke.scala:417)
	at datomicClient.anomaly.AnomalyWrapper.catchAnomaly(AnomalyWrapper.scala:12)
	at datomicClient.anomaly.AnomalyWrapper.catchAnomaly$(AnomalyWrapper.scala:10)
	at datomicClient.Invoke$.catchAnomaly(Invoke.scala:13)
	at datomicClient.Invoke.transact(Invoke.scala:416)
	at datomicClient.Invoke.transact$(Invoke.scala:413)
	at datomicClient.Invoke$.transact(Invoke.scala:13)
	at datomicJava.client.api.sync.Connection.transact(Connection.scala:32)
	at datomicJava.client.api.sync.Connection.transact(Connection.scala:39)
```
Library version: org.scalamolecule:datomic-client-api-java-scala_2.13:1.0.0
Connection type: peer-server

**Comment by marcgrue** [comment]
For Client systems it seems that you have to deploy the transaction function by adding the fully-qualified name under the `:allow` key in your ion-config.edn file before you can call it (see https://docs.datomic.com/cloud/transactions/transaction-functions.html#custom). 

I haven't seen that you can transact the function code literal as you can on Peer. `#db/fn` is not part of the Client api and therefore not recognised which your error seems to indicate.

Haven't tried yet to see if/how one can test a tx function against dev-local, which should be simply to call the code according to the link above.

**Comment by marcgrue** [comment]
Thanks for the link - can you copy this approach?
